---
- name: Test the website
  hosts: webservers
  become: yes
  become_user: root

  tasks:
    - name: Check port 80 is listening on managed node
      wait_for:
        port: 80
        state: started
        timeout: 3

    - name: Verify apache is available remotely
      uri:
        url: "http://{{ ansible_host }}/index.html"

    - name: Stat apache2
      stat:
        path: /usr/sbin/apache2
      register: i

    - name: Fail if apache2 doesn't exist
      assert:
        that:
          - "i.stat.exists"
        fail_msg: "/usr/sbin/apache2 does not exist!"
        success_msg: "/usr/sbin/apache2 exists"

